spring.application.name=jwt-token

spring.data.mongodb.uri=mongodb://localhost:27017/student-curd

jwt.secret =xdEY0pU7jQ4oTp/u2WOZ+XKLW8+WrUUEeYNah/0URi0=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username =sethusp65@gmail.com
spring.mail.password =gmwqduicqaazroec
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#
#spring.security.oauth2.client.registration.google.client-id=29073586555-jiqldarm4o4618pfj7820h9e9ts7idht.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=openid, email, profile
#spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
#
#
#spring.security.oauth2.client.registration.github.client-id= Iv23li879w0xM8w6B6Yz
#spring.security.oauth2.client.registration.github.client-secret=4a7e5c112555d96cc6b3cb50ea265e9e6fe46bb0
#spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
#spring.security.oauth2.client.registration.github.scope=user,repo
#spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
#spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
#spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
#spring.security.oauth2.client.provider.github.user-name-attribute=email


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.jwt=DEBUG

